# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20180516_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mood',
            options={},
        ),
        migrations.RemoveField(
            model_name='mood',
            name='pub_date',
        ),
    ]
