# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20180516_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mood',
            options={'ordering': ('pub_date',)},
        ),
        migrations.AddField(
            model_name='mood',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
